// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6oEUsKA3LEywhC4YCx_RXVkKhafWzDv4',
    appId: '1:162109185280:web:77606bd17392a5043ca7e5',
    messagingSenderId: '162109185280',
    projectId: 'emergency-orchestrator-bef12',
    authDomain: 'emergency-orchestrator-bef12.firebaseapp.com',
    storageBucket: 'emergency-orchestrator-bef12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9G4bdLf5HgnLBcsrT4Kol3MgMTYXnHSg',
    appId: '1:162109185280:android:904782e527344cc03ca7e5',
    messagingSenderId: '162109185280',
    projectId: 'emergency-orchestrator-bef12',
    storageBucket: 'emergency-orchestrator-bef12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCluyUe7rxrxnZVNaxhAsYQw0erOuMOTu4',
    appId: '1:162109185280:ios:081e9df2fa31ce893ca7e5',
    messagingSenderId: '162109185280',
    projectId: 'emergency-orchestrator-bef12',
    storageBucket: 'emergency-orchestrator-bef12.firebasestorage.app',
    iosBundleId: 'com.example.emergencyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCluyUe7rxrxnZVNaxhAsYQw0erOuMOTu4',
    appId: '1:162109185280:ios:081e9df2fa31ce893ca7e5',
    messagingSenderId: '162109185280',
    projectId: 'emergency-orchestrator-bef12',
    storageBucket: 'emergency-orchestrator-bef12.firebasestorage.app',
    iosBundleId: 'com.example.emergencyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6oEUsKA3LEywhC4YCx_RXVkKhafWzDv4',
    appId: '1:162109185280:web:02f2a333c2cd3ae73ca7e5',
    messagingSenderId: '162109185280',
    projectId: 'emergency-orchestrator-bef12',
    authDomain: 'emergency-orchestrator-bef12.firebaseapp.com',
    storageBucket: 'emergency-orchestrator-bef12.firebasestorage.app',
  );
}